languageCode: en-us
title: Van Scoy

# baseURL: //vanscoy.github.io/
relativeURLs: true
# uglyURLs: true
# canonifyURLs: true
disablePathToLower: true

params:
  ieee: 37085411841
  orcid: 0000-0002-8286-2311
  github: vanscoy
  googlescholar: HMBAnMEAAAAJ
  semanticscholar: Bryan-Van-Scoy/3175450
  mathscinet: 1327163
  dblp: 158/5521
  name:
    - first: Bryan
    - Last: Van Scoy

outputs:
  home:
    - HTML
    - JSON